Repository KyoriPowered/indra, pull requests merged in 2023-10, with the labels that each got.

#153 Bump to Gradle 8.4
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  indra-git/src/test/java/net/kyori/indra/git/IndraGitPluginFunctionalTest.java
  indra-testlib/src/main/java/net/kyori/indra/test/IndraFunctionalTestBase.java
Labels: type: dependencies

#154 Fix newLine option with formats that have null `end`
  indra-licenser-spotless/src/main/java/net/kyori/indra/licenser/spotless/internal/IndraSpotlessLicenserExtensionImpl.java
Labels: type: bug

#155 Allow licenser to work on java files in the root package and without imports
  indra-licenser-spotless/src/main/java/net/kyori/indra/licenser/spotless/IndraSpotlessLicenserPlugin.java
Labels: type: enhancement
